name: build
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: build
        run: mvn install
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: Community.jar
          path: target/Community.jar
          if-no-files-found: error

